export type SkillGroup = {
  code: string;
  title: string;
  caption: string;
  items: string[];
};

/** Mirrors the technical skills section of the CV. */
export const skillGroups: SkillGroup[] = [
  {
    code: "CV",
    title: "Vision & ML",
    caption: "Detection, segmentation, OCR, and the spatial logic around them.",
    items: [
      "PyTorch",
      "RF-DETR",
      "YOLOv8",
      "SAM2",
      "PaddleOCR",
      "OpenCV",
      "Object detection",
      "Image segmentation",
      "scikit-learn",
      "NumPy",
    ],
  },
  {
    code: "LLM",
    title: "LLM & Retrieval",
    caption: "Retrieval pipelines and agents that answer from real documents.",
    items: [
      "RAG pipelines",
      "LangChain",
      "Pinecone",
      "ChromaDB",
      "Embeddings",
      "Semantic search",
      "Amazon Bedrock",
      "Amazon Lex",
    ],
  },
  {
    code: "API",
    title: "Backend",
    caption: "Services designed to be versioned, tested, and scaled.",
    items: [
      "FastAPI",
      "Node.js",
      "Express",
      "REST APIs",
      "GraphQL",
      "Async Python",
      "Pydantic",
      "Microservices",
      "WebSockets",
      "LiveKit",
      "WebRTC",
      "JWT / OAuth",
    ],
  },
  {
    code: "UI",
    title: "Frontend",
    caption: "Product surfaces that stay fast as they grow.",
    items: [
      "React",
      "Next.js",
      "TypeScript",
      "Redux Toolkit",
      "React Query",
      "Zustand",
      "Tailwind CSS",
      "shadcn/ui",
      "React Hook Form",
    ],
  },
  {
    code: "DB",
    title: "Data",
    caption: "Schema design and query work, not just an ORM call.",
    items: [
      "PostgreSQL",
      "MongoDB",
      "MySQL",
      "Redis",
      "Vector databases",
      "Schema design",
      "Query optimisation",
      "Indexing",
    ],
  },
  {
    code: "OPS",
    title: "Cloud, DevOps & Testing",
    caption: "Infrastructure that is reproducible, not hand-made.",
    items: [
      "AWS EC2 / S3 / Lambda",
      "SageMaker",
      "API Gateway",
      "Docker",
      "Terraform",
      "Terragrunt",
      "GitHub Actions",
      "CI/CD",
      "Pytest",
      "Jest",
      "Postman",
    ],
  },
];

/** Flat list used by the marquee band. */
export const marqueeSkills = [
  "RF-DETR",
  "SAM2",
  "PaddleOCR",
  "YOLOv8",
  "PyTorch",
  "OpenCV",
  "RAG",
  "LangChain",
  "Pinecone",
  "FastAPI",
  "Next.js",
  "React",
  "TypeScript",
  "Node.js",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Docker",
  "Terraform",
  "GitHub Actions",
  "AWS",
];
